name: GitHub Actions Test - 20221010 - Pass on Critical / High
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
    build:
        # ...
        runs-on: ubuntu-latest
        steps:

         - name: Check out the repo
           uses: actions/checkout@v2

         - name: Get short SHA
           run: echo "GHA_SHA=${GITHUB_SHA:0:7}" >> $GITHUB_ENV

         - name: Build
           uses: docker/build-push-action@v2
           with:
             tags: securethecloud/my-tweet-app-lacework:${{ env.GHA_SHA }},securethecloud/my-tweet-app-lacework:latest
             load: true

         - name: Scan container images for vulnerabitilies using Lacework
           uses: lacework/lw-scanner-action@v1.1.0 
           with:
             LW_ACCOUNT_NAME: ${{ secrets.LW_ACCOUNT_NAME }} 
             LW_ACCESS_TOKEN: ${{ secrets.LW_ACCESS_TOKEN }}
             IMAGE_NAME: securethecloud/my-tweet-app-lacework
             IMAGE_TAG: ${{ env.GHA_SHA }}
             SAVE_RESULTS_IN_LACEWORK: true
             SAVE_BUILD_REPORT: true
             BUILD_REPORT_FILE_NAME: lwreport.html
       	     SCAN_LIBRARY_PACKAGES: true
         
